#!/usr/bin/env python3
"""Generate a Y-axis step-loss characterization G-code file."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_CONFIG_PATH = SCRIPT_DIR / "printer.cfg"
OUTPUT_FILENAME_PREFIX = "y_step_loss_characterization"


@dataclass(frozen=True)
class YAxisConfig:
    position_endstop: float
    position_min: float
    position_max: float
    max_velocity: float
    max_accel: float
    square_corner_velocity: float


@dataclass(frozen=True)
class TestPlan:
    accel_levels: tuple[int, ...] = (7000, 8000)
    cycles_per_level: int = 20
    away_distance_mm: float = 90.0
    endstop_gap_mm: float = 5.0
    away_velocity_mm_s: float = 350.0
    away_accel_mm_s2: float = 1000.0
    test_velocity_mm_s: float = 500.0
    creep_velocity_mm_s: float = 20.0
    creep_accel_mm_s2: float = 500.0
    dwell_ms: int = 100
    endstop_key: str = "stepper_y"


def _section(config_text: str, name: str) -> str:
    match = re.search(
        rf"^\[{re.escape(name)}\]\n(?P<body>.*?)(?=^\[|\Z)",
        config_text,
        flags=re.MULTILINE | re.DOTALL,
    )
    if match is None:
        raise ValueError(f"Missing [{name}] section")
    return match.group("body")


def _setting_float(section: str, setting_name: str) -> float:
    match = re.search(
        rf"^\s*{re.escape(setting_name)}\s*:\s*(?P<value>\S+)\s*$",
        section,
        flags=re.MULTILINE,
    )
    if match is None:
        raise ValueError(f"Missing setting {setting_name}")
    return float(match.group("value"))


def load_y_axis_config(config_path: Path = DEFAULT_CONFIG_PATH) -> YAxisConfig:
    config_text = config_path.read_text(encoding="utf-8")
    printer = _section(config_text, "printer")
    stepper_y = _section(config_text, "stepper_y")
    return YAxisConfig(
        position_endstop=_setting_float(stepper_y, "position_endstop"),
        position_min=_setting_float(stepper_y, "position_min"),
        position_max=_setting_float(stepper_y, "position_max"),
        max_velocity=_setting_float(printer, "max_velocity"),
        max_accel=_setting_float(printer, "max_accel"),
        square_corner_velocity=_setting_float(printer, "square_corner_velocity"),
    )


def _format_float(value: float) -> str:
    return f"{value:.3f}"


def _feedrate(velocity_mm_s: float) -> str:
    return f"{velocity_mm_s * 60.0:.0f}"


def timestamped_output_path(
    output_dir: Path = SCRIPT_DIR,
    now: datetime | None = None,
) -> Path:
    current_time = now or datetime.now()
    return output_dir / f"{OUTPUT_FILENAME_PREFIX}_{current_time:%Y%m%d_%H%M%S}.gcode"


def _validate_plan(axis: YAxisConfig, plan: TestPlan) -> None:
    if plan.cycles_per_level <= 0:
        raise ValueError("cycles_per_level must be positive")
    if not plan.accel_levels:
        raise ValueError("accel_levels must not be empty")
    if sorted(plan.accel_levels) != list(plan.accel_levels):
        raise ValueError("accel_levels must be sorted ascending")
    if plan.endstop_gap_mm <= 0:
        raise ValueError("endstop_gap_mm must be positive")
    if plan.away_distance_mm <= plan.endstop_gap_mm:
        raise ValueError("away_distance_mm must be greater than endstop_gap_mm")

    y_endstop = axis.position_endstop
    y_gap = y_endstop + plan.endstop_gap_mm
    y_away = y_endstop + plan.away_distance_mm
    for label, y in (
        ("endstop", y_endstop),
        ("gap", y_gap),
        ("away", y_away),
    ):
        if not axis.position_min <= y <= axis.position_max:
            raise ValueError(
                f"{label} Y target {y:.3f} is outside configured Y range "
                f"{axis.position_min:.3f}..{axis.position_max:.3f}"
            )


def generate_gcode(axis: YAxisConfig, plan: TestPlan = TestPlan()) -> str:
    _validate_plan(axis, plan)

    y_endstop = axis.position_endstop
    y_gap = y_endstop + plan.endstop_gap_mm
    y_away = y_endstop + plan.away_distance_mm
    total_checks = len(plan.accel_levels) * plan.cycles_per_level

    lines = [
        "; Y step-loss characterization generated by generate_y_step_loss_test_gcode.py",
        f"; Endstop verification key: {plan.endstop_key}",
        f"; Y endstop: {_format_float(y_endstop)}",
        f"; Y away distance: {_format_float(plan.away_distance_mm)}",
        f"; Y away target: {_format_float(y_away)}",
        f"; Y high-accel return target: {_format_float(y_gap)}",
        f"; Accel levels: {', '.join(str(accel) for accel in plan.accel_levels)}",
        f"; Cycles per level: {plan.cycles_per_level}",
        f"; Total endstop checks: {total_checks}",
        "M117 Y step-loss characterization",
        f'RESPOND TYPE=echo MSG="Y step-loss characterization: homing Y, then running {total_checks} endstop checks."',
        "G90",
        "M400",
        "G28 Y",
        "M400",
    ]

    check_index = 0
    for accel in plan.accel_levels:
        lines.extend(
            [
                f'RESPOND TYPE=echo MSG="Y step-loss level: accel {accel} mm/s^2, {plan.cycles_per_level} cycles."',
                (
                    "SET_VELOCITY_LIMIT "
                    f"VELOCITY={plan.away_velocity_mm_s:g} "
                    f"ACCEL={plan.away_accel_mm_s2:g} "
                    f"SQUARE_CORNER_VELOCITY={axis.square_corner_velocity:g}"
                ),
            ]
        )
        for cycle in range(1, plan.cycles_per_level + 1):
            check_index += 1
            lines.extend(
                [
                    f"; Check {check_index}/{total_checks}: accel={accel} cycle={cycle}",
                    f"G1 Y{_format_float(y_away)} F{_feedrate(plan.away_velocity_mm_s)}",
                    "M400",
                    (
                        "SET_VELOCITY_LIMIT "
                        f"VELOCITY={plan.test_velocity_mm_s:g} "
                        f"ACCEL={accel:g} "
                        f"SQUARE_CORNER_VELOCITY={axis.square_corner_velocity:g}"
                    ),
                    f"G1 Y{_format_float(y_gap)} F{_feedrate(plan.test_velocity_mm_s)}",
                    "M400",
                    (
                        "SET_VELOCITY_LIMIT "
                        f"VELOCITY={plan.creep_velocity_mm_s:g} "
                        f"ACCEL={plan.creep_accel_mm_s2:g} "
                        f"SQUARE_CORNER_VELOCITY={axis.square_corner_velocity:g}"
                    ),
                    f"G1 Y{_format_float(y_endstop)} F{_feedrate(plan.creep_velocity_mm_s)}",
                    "M400",
                    f"G4 P{plan.dwell_ms}",
                    "QUERY_ENDSTOPS",
                    (
                        "Y_STEP_LOSS_ASSERT_ENDSTOP "
                        f"ACCEL={accel} CYCLE={cycle} STEP={check_index}"
                    ),
                    (
                        "SET_VELOCITY_LIMIT "
                        f"VELOCITY={plan.away_velocity_mm_s:g} "
                        f"ACCEL={plan.away_accel_mm_s2:g} "
                        f"SQUARE_CORNER_VELOCITY={axis.square_corner_velocity:g}"
                    ),
                ]
            )

    lines.extend(
        [
            "M400",
            (
                "SET_VELOCITY_LIMIT "
                f"VELOCITY={axis.max_velocity:g} "
                f"ACCEL={axis.max_accel:g} "
                f"SQUARE_CORNER_VELOCITY={axis.square_corner_velocity:g}"
            ),
            f'RESPOND TYPE=echo MSG="Y step-loss characterization passed: {total_checks} endstop checks completed."',
            "M117 Y step-loss passed",
            "",
        ]
    )
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a Y-axis step-loss characterization G-code file."
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG_PATH)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path. Defaults to a unique timestamped G-code file.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=SCRIPT_DIR,
        help="Directory for the timestamped output file when --output is omitted.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    axis = load_y_axis_config(args.config)
    gcode = generate_gcode(axis)
    output_path = args.output or timestamped_output_path(args.output_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(gcode, encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
