[server]
domain-name=local
use-ipv4=yes
use-ipv6=yes
allow-interfaces=eth0,wlan0

[wide-area]
enable-wide-area=yes

[publish]
disable-publishing=no
disable-user-service-publishing=no
add-service-cookie=yes
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes
