#### crowsnest.conf
#### Webcam preview stream for Mege Ender 3 V3 KE IDEX.

[crowsnest]
log_level: verbose
rollover_on_start: true
no_proxy: false

[cam printer]
mode: ustreamer
port: 8080
device: /dev/v4l/by-id/usb-Aukey-PC-LM1E_Camera_Aukey-PC-LM1E_Camera-video-index0
resolution: 1280x720
max_fps: 15
