# Minimal Moonraker configuration; extend with your printer settings.

[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
	127.0.0.0/8
	10.0.0.0/8
	172.16.0.0/12
	192.168.0.0/16

[octoprint_compat]

[file_manager]
enable_object_processing: true

[machine]
provider: systemd_dbus

[webcam Printer Camera]
location: printer
enabled: True
service: mjpegstreamer
target_fps: 15
target_fps_idle: 5
stream_url: /webcam/?action=stream
snapshot_url: /webcam/?action=snapshot
flip_horizontal: False
flip_vertical: False
rotation: 0
aspect_ratio: 16:9

[update_manager]
enable_auto_refresh: True

[update_manager crowsnest]
type: git_repo
path: /opt/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
primary_branch: v5
managed_services: crowsnest
system_dependencies: system-dependencies.json
virtualenv: /home/pi/crowsnest-env
requirements: requirements.txt
