#!/bin/bash
# This script was generated by newshscript.sh

set -euo pipefail
trap 'echo "Script $0 failed at line $LINENO" >&2' ERR


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SCRIPT_FULLPATH="$(realpath "$0")"


# ${SCRIPT_DIR}/../shellforgepy/freecad_python.sh -m shellforgepy run "$@"

python -m shellforgepy run $@