"""Config loader for pinout diagrams."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from .svg import DEFAULT_COLOR_MAP, DEFAULT_SVG_MARGINS_PX, SvgMarginsPx


@dataclass(frozen=True)
class PinoutProject:
    """Normalized pinout project loaded from config."""

    pin_positions: dict[str, tuple[float, float]]
    connections: list[dict[str, Any]]
    color_map: dict[str, str]
    basename: str
    version_label: str | None = None
    notes_text: str | None = None
    svg_margins_px: SvgMarginsPx = DEFAULT_SVG_MARGINS_PX


def _as_xy(value: Any, *, context: str) -> tuple[float, float]:
    if not isinstance(value, (list, tuple)) or len(value) != 2:
        raise ValueError(f"{context} must be [x, y], got: {value!r}")
    return float(value[0]), float(value[1])


def _load_raw_config(path: Path) -> dict[str, Any]:
    raw_text = path.read_text(encoding="utf-8")
    if path.suffix.lower() == ".json":
        data = json.loads(raw_text)
    else:
        data = yaml.safe_load(raw_text)

    if not isinstance(data, dict):
        raise ValueError(f"Config root must be a mapping, got: {type(data).__name__}")
    return data


def _expand_pin_sets(pin_sets: Any) -> dict[str, tuple[float, float]]:
    if pin_sets is None:
        return {}
    if not isinstance(pin_sets, list):
        raise ValueError("pin_sets must be a list")

    generated: dict[str, tuple[float, float]] = {}
    direction_vectors = {
        "up": (0.0, 1.0),
        "down": (0.0, -1.0),
        "right": (1.0, 0.0),
        "left": (-1.0, 0.0),
    }

    for idx, pin_set in enumerate(pin_sets):
        if not isinstance(pin_set, dict):
            raise ValueError(f"pin_sets[{idx}] must be a mapping")

        origin = _as_xy(pin_set.get("origin"), context=f"pin_sets[{idx}].origin")
        names = pin_set.get("pins", pin_set.get("names"))
        if not isinstance(names, list) or not names:
            raise ValueError(f"pin_sets[{idx}] requires non-empty pins/names list")

        direction = str(pin_set.get("direction", "up")).lower()
        if direction not in direction_vectors:
            raise ValueError(
                f"pin_sets[{idx}].direction must be one of {list(direction_vectors)}"
            )

        step = float(pin_set.get("step", 1.0))
        if step <= 0:
            raise ValueError(f"pin_sets[{idx}].step must be > 0")

        prefix = str(pin_set.get("prefix", ""))
        dx, dy = direction_vectors[direction]
        for pos, name_value in enumerate(names):
            name = str(name_value)
            pin_name = f"{prefix}{name}" if prefix else name
            pin_pos = (origin[0] + dx * pos * step, origin[1] + dy * pos * step)
            if pin_name in generated:
                raise ValueError(f"Duplicate pin generated by pin_sets: {pin_name}")
            generated[pin_name] = pin_pos

    return generated


def _load_explicit_pins(raw_pins: Any) -> dict[str, tuple[float, float]]:
    if raw_pins is None:
        return {}
    if not isinstance(raw_pins, dict):
        raise ValueError("pins must be a mapping of pin_name: [x, y]")

    pins: dict[str, tuple[float, float]] = {}
    for pin_name, raw_xy in raw_pins.items():
        pins[str(pin_name)] = _as_xy(raw_xy, context=f"pins.{pin_name}")
    return pins


def _raise_if_duplicate_pin_coordinates(
    pin_positions: dict[str, tuple[float, float]],
) -> None:
    coordinate_to_pins: dict[tuple[float, float], list[str]] = {}
    for pin_name, pin_position in pin_positions.items():
        coordinate_to_pins.setdefault(pin_position, []).append(pin_name)

    duplicate_coordinate_groups = [
        (coordinate, sorted(pin_names))
        for coordinate, pin_names in coordinate_to_pins.items()
        if len(pin_names) > 1
    ]
    if not duplicate_coordinate_groups:
        return

    duplicate_coordinate_groups.sort(key=lambda item: (item[0][0], item[0][1], item[1]))
    details = "; ".join(
        f"{coordinate}: {', '.join(pin_names)}"
        for coordinate, pin_names in duplicate_coordinate_groups
    )
    raise ValueError(f"Duplicate pin coordinates detected: {details}")


def _normalize_connections(raw_connections: Any) -> list[dict[str, Any]]:
    if not isinstance(raw_connections, list) or not raw_connections:
        raise ValueError("wires/connections must be a non-empty list")

    normalized: list[dict[str, Any]] = []
    for i, wire in enumerate(raw_connections):
        if not isinstance(wire, dict):
            raise ValueError(f"wire[{i}] must be a mapping")
        if "from" not in wire or "to" not in wire:
            raise ValueError(f"wire[{i}] must define 'from' and 'to'")

        normalized_wire: dict[str, Any] = {
            "from": str(wire["from"]),
            "to": str(wire["to"]),
            "type": str(wire.get("type", wire.get("kind", "default"))),
        }
        if "color" in wire and wire["color"] is not None:
            normalized_wire["color"] = str(wire["color"])

        normalized.append(normalized_wire)
    return normalized


def _as_non_negative_margin(value: Any, *, context: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{context} must be a non-negative number")

    margin = float(value)
    if margin < 0:
        raise ValueError(f"{context} must be >= 0")
    return margin


def _normalize_svg_margins_px(raw_margins: Any) -> SvgMarginsPx:
    if raw_margins is None:
        return DEFAULT_SVG_MARGINS_PX

    if isinstance(raw_margins, (int, float)) and not isinstance(raw_margins, bool):
        margin = _as_non_negative_margin(raw_margins, context="metadata.svg_margins_px")
        return margin, margin, margin, margin

    if not isinstance(raw_margins, dict):
        raise ValueError(
            "metadata.svg_margins_px must be a number or mapping with "
            "left/right/top/bottom keys"
        )

    allowed_keys = {"left", "right", "top", "bottom"}
    unknown_keys = sorted(
        str(key) for key in raw_margins if str(key) not in allowed_keys
    )
    if unknown_keys:
        raise ValueError(f"Unknown metadata.svg_margins_px keys: {unknown_keys}")

    values = {
        "left": DEFAULT_SVG_MARGINS_PX[0],
        "right": DEFAULT_SVG_MARGINS_PX[1],
        "top": DEFAULT_SVG_MARGINS_PX[2],
        "bottom": DEFAULT_SVG_MARGINS_PX[3],
    }
    for key, raw_value in raw_margins.items():
        key_text = str(key)
        values[key_text] = _as_non_negative_margin(
            raw_value, context=f"metadata.svg_margins_px.{key_text}"
        )

    return values["left"], values["right"], values["top"], values["bottom"]


def load_pinout_config(config_path: str | Path) -> PinoutProject:
    """Load and validate pinout config from YAML or JSON."""
    path = Path(config_path)
    data = _load_raw_config(path)

    pin_positions = _expand_pin_sets(data.get("pin_sets"))
    explicit_pins = _load_explicit_pins(data.get("pins"))
    for pin_name in explicit_pins:
        if pin_name in pin_positions:
            raise ValueError(f"Duplicate pin '{pin_name}' from pin_sets and pins")
    pin_positions.update(explicit_pins)
    if not pin_positions:
        raise ValueError("Config must define at least one pin via pin_sets or pins")
    _raise_if_duplicate_pin_coordinates(pin_positions)

    raw_connections = data.get("wires", data.get("connections"))
    connections = _normalize_connections(raw_connections)
    unknown_pins = sorted(
        {
            endpoint
            for connection in connections
            for endpoint in (connection["from"], connection["to"])
            if endpoint not in pin_positions
        }
    )
    if unknown_pins:
        raise ValueError(f"Connections reference unknown pins: {unknown_pins}")

    color_map = dict(DEFAULT_COLOR_MAP)
    raw_color_map = data.get("color_map", {})
    if raw_color_map:
        if not isinstance(raw_color_map, dict):
            raise ValueError("color_map must be a mapping")
        color_map.update({str(k): str(v) for k, v in raw_color_map.items()})

    metadata = data.get("metadata", {})
    if metadata is None:
        metadata = {}
    if not isinstance(metadata, dict):
        raise ValueError("metadata must be a mapping")

    basename = str(data.get("basename", metadata.get("basename", "pinout")))
    version_label = data.get("version_label", metadata.get("version_label"))
    notes_text = data.get("notes_text", metadata.get("notes"))
    svg_margins_px = _normalize_svg_margins_px(metadata.get("svg_margins_px"))

    return PinoutProject(
        pin_positions=pin_positions,
        connections=connections,
        color_map=color_map,
        basename=basename,
        version_label=str(version_label) if version_label is not None else None,
        notes_text=str(notes_text) if notes_text is not None else None,
        svg_margins_px=svg_margins_px,
    )
